### ISSUE TITLE
Persistent measurements.

### ISSUE THREAD

**Issue by typesupply** [typesupply/lasermeasure#34]
I often find myself measuring the same things over and over. It would be nice if I could link 2 or more points and have the measurements show up whenever the trigger key is pressed (or at all times). This information shown would be the same as the live information: width, height, matched named values. The links could be saved in the glyph lib as collections of identifiers:

```python
"com.typesupply.LaserMeasure.links" : [
    ["identifier1", "identifier2"],
    ["identifier7", "identifier8", "identifier9"],
]
```

- _How are these links created?_ Idea: When the trigger key is pressed and a selection is pressed, return would create a new link. (Can this actually be captured with a subscriber?)
- _How are these links destroyed?_ Idea: Do the same as how links are created, but add a modifier?
- _How are these links visualized?_ Idea: Just draw a line underneath them using a rotating color system like the one used for matched segments. Add a dash or something to differentiate from matched segments.

**Comment by typesupply** [comment]
cc @ryanbugden

**Comment by ryanbugden** [comment]
Would this be the same trigger key as the main one, or a separate one just for persistent things + links?

The main hurdle I see (which I'm sure you have ideas for) is how to intuitively allow both persistent and temporary measurements.

**Comment by typesupply** [comment]
> Would this be the same trigger key as the main one, or a separate one just for persistent things + links?

I'm not sure. I need to see if will even be possible with one key. I'm not sure how subscriber will work if watching for a key down and then another key down comes along. For example, if the user makes a selection and hits `d` to pull up the measurements and then they hit `return` to make a persistent link, will subscriber be able to handle that?

**Comment by ryanbugden** [comment]
Oh yeah, that sounds like a good interaction idea to me (similar to `~ + Shift` for RF preview mode in Glyph Editor), and I think Subscriber should be able to handle it!

Try the below. Press and hold 'd' and then press Return.

```python
from mojo.subscriber import Subscriber, registerGlyphEditorSubscriber


TRIGGER = 'd'

class ExampleSubscriber(Subscriber):
    
    debug = True
    
    def build(self):
        self.trigger_down = False
        self.return_down = False
    
    def glyphEditorDidKeyDown(self, info):
        key = info['iterations'][0]['deviceState']['keyDownWithoutModifiers']
        
        # print("DOWN", list(key))
        if key == TRIGGER:
            # print("key was trigger")
            self.trigger_down = True
        elif key == '\r':
            # print("key was return")
            self.return_down = True
            
        # Pressed TRIGGER and enter?
        if self.trigger_down and self.return_down:
            print("LOCK AND LINK ’EM!")
            
        # print("trigger down?", self.trigger_down)
        # print("return down?", self.trigger_down)
        # print()
        
    def glyphEditorDidKeyUp(self, info):
        key = info['iterations'][0]['deviceState']['keyDownWithoutModifiers']
        
        # print("UP", list(key))
        if key == TRIGGER:
            # print("key was trigger")
            self.trigger_down = False
        elif key == '\r':
            # print("key was return")
            self.return_down = False
            
        # print("trigger down?", self.trigger_down)
        # print("return down?", self.trigger_down)
        # print()

registerGlyphEditorSubscriber(ExampleSubscriber)
```

**Comment by typesupply** [comment]
I think I'm going to limit this to measurement between two points for now. Visualizing the link between more than two points is making my head hurt.

**Comment by ryanbugden** [comment]
Oh, as in if you want to add a second persistent measurement, it will overwrite the last stored one?

**Comment by typesupply** [comment]
No, sorry I wasn't clear. I mean, if you have more than two points selected, that can't be stored as a link. I want to keep it simple as links between just two points for now. You can have as many two point links as you want.

**Comment by ryanbugden** [comment]
Gotcha. I'll have to try out what you have in mind. In my mind, the (native) point-selection is and would always be disregarded by Laser Measure, and the extension would effectively act the same—just keeping lasers on after the trigger character is pressed (thus having the ability to add more lasers [temporary or persistent]), and having the persistent lasers stay associated with the points that they initially measured. 

I'm sure we're probably talking about the same thing though.

**Comment by typesupply** [comment]
Actually, it can. :) The selected points will show up in an outlined box below the solid box.

<img width="571" alt="image" src="https://github.com/typesupply/lasermeasure/assets/4992934/e60ef920-2953-4379-b957-22a47ab52b32">

**Comment by ryanbugden** [comment]
Yeah, sorry please ignore me—forgot it had this great feature

**Comment by typesupply** [comment]
Okay. I have lines showing up now. Now for the hard part: where should the measurement text appear?

- in the middle of the line between points?
- offset from the line? what is the offset?
- some combination of both depending on the angle of the line?

If you have any thoughts, I'd love to know. I'm going to just rough something in for now.

**Comment by ryanbugden** [comment]
> * in the middle of the line between points?
> * offset from the line? what is the offset?
> * some combination of both depending on the angle of the line?

My vote would be the first option!

**Comment by typesupply** [comment]
<img width="1170" alt="image" src="https://github.com/typesupply/lasermeasure/assets/4992934/9d64643b-fddf-4431-a7d2-d567acfe994c">

Point to point indicators are working. Ugly, but working.

**Comment by typesupply** [comment]
<img width="1192" alt="image" src="https://github.com/typesupply/lasermeasure/assets/4992934/23705f85-3d91-46a9-9da4-0e5a48a332d7">

**Comment by ryanbugden** [comment]
🙌 I like how the dashed line kind of feels like a locked measurement relationship. Or at least something different from the other stuff.

**Comment by typesupply** [comment]
This is now pushed to the development branch. Give it a try and see what you think. I had to add stuff to the settings window and that led me to reorganize the window into sections. Feel free to redesign it. Also, if you have a better name than "persistent measurements" I'd love to know. `p e r s i s t e n t` is annoying to type.

**Comment by typesupply** [comment]
I'm going to close this since the base behavior seems to be working.

**Comment by ryanbugden** [comment]
This is super cool Tal! I had fun testing it, and I have several thoughts you may find worth considering:

1. **Selection paradigm.** 
Adding persistent measurements seems to use selected points. I think in the realm of Laser Measure, I expected `[trigger] + Enter` to lock the current “laser” measurement, not what points you may have selected elsewhere. As far as info on selected points goes, LM kind of already provided that benefit before (You could laser-measure somewhere else while you have points selected, then compare the numbers).
2. **Not just point relationships.** 
Maybe an additional flavor of a persistent measurement could be keeping the floating laser crosshair (Not necessarily attached to specific points. Just generally measuring in a particular area.
3. **More persistence.** 
Letting go of the trigger hides the persistent measurements again, and I think there would be a lot of benefit to them being truly persistent and staying on-screen. My thought is that maybe you want to measure a weird stroke, and keep the measurement on while you change the weight of the stroke. Currently, you'd have to keep repeatedly hitting (or holding) the trigger to keep checking on it.
4. **The process of removing persistent measurements.** 
I think `[trigger] + Escape` (or maybe even just `Escape`) could remove all persistent measurements, rather than having to manually go back to each one and removing it with `trigger + Escape`.
5. **Measurement display.** 
The measurement text layers currently don’t show up until `mouseMoved`. I think `keyDown` should probably bring the measurements up.
6. **Color.** 
[Less consequential] Maybe persistent measurements don’t have the be a different color than the Laser. I see it as a kind of persistent active laser. I think the change to dashed lines might be enough to feel like you’re locking it in. That said you already did the work of allowing the pref, so might as well keep it :)

Would love to hear your thoughts on these things. Would be happy to help work on whatever also resonates with you.

**Comment by ryanbugden** [comment]
As for Item 2, there could potentially be a pref "Always Show Locked Measurement".

**Comment by ryanbugden** [comment]
I probably should have broken my last comment into multiple issues, sorry. I have coded a suggestion as to how persistent measurements should be handled. Please let me know what you think!
